export const COPY = {
  appName: 'El Panal del Tiempo',
  welcome: {
    title: '¡Bienvenido al panal!',
    subtitle: '¿Quién sos vos?',
    confirm: 'Entrar al panal',
  },
  nav: {
    timeline: 'Línea de tiempo',
    pending: 'Pendientes',
  },
  timeline: {
    empty: 'Todavía no hay recuerdos validados. ¡Sumá el primero!',
    searchPlaceholder: 'Buscar por mes o año...',
    searchLabel: 'Buscar una fecha con recuerdos',
    searchNoResults: 'No hay recuerdos en esa fecha.',
    delete: 'Borrar recuerdo',
  },
  eventForm: {
    createTitle: 'Nuevo recuerdo',
    editTitle: 'Editar recuerdo',
    titleLabel: 'Título',
    titlePlaceholder: 'Ej: El primer viaje juntos',
    descriptionLabel: 'Descripción',
    descriptionPlaceholder: 'Contá qué pasó...',
    monthLabel: 'Mes',
    yearLabel: 'Año',
    submit: 'Guardar',
    cancel: 'Cancelar',
  },
  pending: {
    mineTitle: 'Tus recuerdos esperando validación',
    mineEmpty: 'No tenés recuerdos pendientes.',
    toValidateTitle: 'Recuerdos para validar',
    toValidateEmpty: '¡Estás al día! No hay nada para validar.',
    validate: 'Validar',
    review: 'Marcar para revisar',
    reviewCommentPlaceholder: 'Contale a quien lo creó qué falta...',
    edit: 'Editar',
    delete: 'Borrar',
    statusValidated: 'Validado',
    statusPending: 'Pendiente',
    statusReview: 'A revisar',
  },
  confirmDelete: {
    title: '¿Borrar este recuerdo?',
    message: 'Esta acción no se puede deshacer y desaparece para todo el panal.',
    confirm: 'Borrar',
  },
  assisted: {
    enter: 'Modo simple',
    exit: 'Salir del modo simple',
    listen: 'Escuchar',
    prev: 'Anterior',
    next: 'Siguiente',
    createdBy: 'Lo subió',
  },
  addEvent: 'Agregar recuerdo',
} as const;
