export const COPY = {
  appName: 'El Panal del Tiempo',
  welcome: {
    title: '¡Bienvenido al panal!',
    subtitle: '¿Quién sos vos?',
    confirm: 'Entrar al panal',
  },
  nav: {
    timeline: 'Línea de tiempo',
    pending: 'Pendientes',
  },
  timeline: {
    empty: 'Todavía no hay recuerdos validados. ¡Sumá el primero!',
    searchPlaceholder: 'Buscar por mes o año...',
    searchLabel: 'Buscar una fecha con recuerdos',
    searchNoResults: 'No hay recuerdos en esa fecha.',
    collapseYear: 'Contraer',
    expandYear: 'Expandir',
  },
  eventForm: {
    createTitle: 'Nuevo recuerdo',
    editTitle: 'Editar recuerdo',
    titleLabel: 'Título',
    titlePlaceholder: 'Ej: El primer viaje juntos',
    descriptionLabel: 'Descripción',
    descriptionPlaceholder: 'Contá qué pasó...',
    monthLabel: 'Mes',
    yearLabel: 'Año',
    submit: 'Guardar',
    cancel: 'Cancelar',
  },
  pending: {
    mineTitle: 'Tus recuerdos esperando validación',
    mineEmpty: 'No tenés recuerdos pendientes.',
    toValidateTitle: 'Recuerdos para validar',
    toValidateEmpty: '¡Estás al día! No hay nada para validar.',
    validate: 'Validar',
    review: 'Marcar para revisar',
    reviewCommentPlaceholder: 'Contale a quien lo creó qué falta...',
    edit: 'Editar',
    statusValidated: 'Validado',
    statusPending: 'Pendiente',
    statusReview: 'A revisar',
  },
  accessibility: {
    panelTitle: 'Accesibilidad',
    largeText: 'Texto grande',
    highContrast: 'Alto contraste',
    reduceMotion: 'Reducir movimiento',
    simplified: 'Modo simplificado',
    close: 'Cerrar',
  },
  addEvent: 'Agregar recuerdo',
} as const;
